# Generated by Django 3.2.5 on 2021-07-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210717_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-created',)},
        ),
    ]
