"""
Django settings for code2hell project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
# import by me 
import os
from django.contrib.messages import constants as messages
from os import environ
# import django_heroku
# import dj_database_url



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--nv99sotgsig09l_0dzei6k^!nj+$@vp(fr+p_m#jsow&yhp))'
# SECRET_KEY = environ['secret_key'] #for heroku

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['code2hell.herokuapp.com']
ALLOWED_HOSTS = ['*']

# FOR  SITEMAPS
SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
      # user app
    'blog.apps.BlogConfig',
    'taggit',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'home.apps.HomeConfig', 
    'django.contrib.humanize', #FOR SHOWING TIME LIKE 2 HOURS AGO IN COMMENT BOX
    'django.contrib.postgres',
    'social_django',
    # 'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'code2hell.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'code2hell.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        #    postgresql
        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'NAME':'code2hell',
        # 'USER':'code2hell',
        # 'PASSWORD':'124421',                          
        # 'HOST': '',
        # 'PORT': '5432',

        # FOR HEROKU
        # 'NAME':'db3msi7nkra2sp',
        # 'USER':'ztgcotptkquwmg',
        # 'PASSWORD':'a53f20a151f0d0fff30c91af6f2e6047003e7deb06c7f617703c4438148c9002',
        # 'HOST':'ec2-35-174-56-18.compute-1.amazonaws.com',
        # 'PORT':'5432',
    # },
    #   'users': {
    #     #    postgresql
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME':'code2hell',
    #     'USER':'code2hell',
    #     'PASSWORD':'124421'
    }
}
# for heroku db
# import dj_database_url

# DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# django_heroku.settngs(locals())

# ***import by me ****
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,  "static"),
]




# ***import by me ****
MESSAGE_TAGS = {
    messages.ERROR:'danger'
}

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'abc@email.com'
EMAIL_HOST_PASSWORD = 'django1234'
EMAIL_USE_TLS = True
# EMAIL_USE_SSL

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






# AUTHENTICATION_BACKENDS- its a class provide two method 1.authenticate(request, user) and 2.get_user(user-id)
AUTHENTICATION_BACKENDS=['django.contrib.auth.backends.ModelBackend',
                        #  'account.authentication.EmailAuthBackend',
                         'social_core.backends.facebook.FacebookOAuth2',
                         'social_core.backends.google.GoogleOAuth2',
			 ]

SOCIAL_AUTH_FACEBOOK_KEY = '347199637039934'
SOCIAL_AUTH_FACEBOOK_SECRET = 'c6ab498008829e813b0d5a3d47d9367c'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '538129904******************175nob0ijj7tlvbftaom6cglh.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '****************************'